version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      # MAPEAR A PASTA INTEIRA PARA DESENVOLVIMENTO LOCAL
      - .:/app
      - ./src:/app/src
      - ./test:/app/test